version: "2"

services:
  unbound:
    image: eugenmayer/unbound:1.8
    volumes:
    - ./unbound/01_records.conf:/etc/unbound/conf.d/01_records.conf
    - ./unbound/02_forward.conf:/etc/unbound/conf.d/02_forward.conf
    ports:
    - ${DNS_PORT}:53
    - ${DNS_PORT}:53/udp
  traefik:
    image: eugenmayer/traefik
    environment:
      # enable file based rules for our home services
      TRAEFIK_FILE_ENABLE: 'true'
      # enable Lets-Encrypt
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ACME_CHALLENGE: 'dns'
      # see .env and https://github.com/EugenMayer/docker-image-traefik#acme
      TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER: "${TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER}"
      TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS: "${TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS}"
      ###  below are test server adjustments
      # use the ACME staging server
      TRAEFIK_ACME_CASERVER: "https://acme-staging-v02.api.letsencrypt.org/directory"
      # enable https only mode for auto-redirects
      TRAEFIK_HTTPS_ENABLE: 'only'
      TRAEFIK_ADMIN_ENABLE: 'true'
      # if you want to also expose other docker containers in the docker-engine
      # TRAEFIK_DOCKER_ENABLE: 'true'
    volumes:
    - ./traefik:/mnt/filestorage
    - certs:/mnt/certs
    - acme:/mnt/acme
    # mount our docker socket so our docker container can be discovered
    #- /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 80:80
    - 443:443

volumes:
  acme:
  certs:
