version: '3'

services:
  unbound:
    image: ghcr.io/eugenmayer/unbound:1.17-1
    volumes:
      - ${UNBOUND_STORAGE:-./unbound-examples}/01_records.conf:/etc/unbound/conf.d/01_records.conf
      - ${UNBOUND_STORAGE:-./unbound-examples}/02_forward.conf:/etc/unbound/conf.d/02_forward.conf
    ports:
      - ${DNS_PORT:-55}:53
      - ${DNS_PORT:-55}:53/udp
    labels:
      # do not expose this service via an auto-rule - needed since TRAEFIK_DOCKER_EXPOSEDBYDEFAULT=true
      traefik.enable: false
volumes:
  acme:
  certs:

networks:
  default:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik}
