version: "3"

services:
  unbound:
    image: ghcr.io/eugenmayer/unbound:1.17-1
    volumes:
      - ${UNBOUND_STORAGE:-./unbound-examples}/01_records.conf:/etc/unbound/conf.d/01_records.conf
      - ${UNBOUND_STORAGE:-./unbound-examples}/02_forward.conf:/etc/unbound/conf.d/02_forward.conf
    ports:
      - ${DNS_PORT:-55}:53
      - ${DNS_PORT:-55}:53/udp
    labels: 
      # do not expose this service via an auto-rule - needed since TRAEFIK_DOCKER_EXPOSEDBYDEFAULT=true
      traefik.enable: false
  traefik:
    restart: always
    image: ghcr.io/eugenmayer/traefik:2.x
    environment:
      TRAEFIK_HTTPS_ENABLE: 'only'

      # ACME
      TRAEFIK_ACME_ENABLE: 'true'
      TRAEFIK_ADMIN_ENABLE: 'true'

      TRAEFIK_ACME_CHALLENGE: 'dns'
      TRAEFIK_ACME_CHALLENGE_DNS_PROVIDER: 'cloudflare'
      TRAEFIK_ACME_CHALLENGE_DNS_DELAY: 0
      TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS: ${TRAEFIK_ACME_CHALLENGE_DNS_CREDENTIALS}
      TRAEFIK_ACME_EMAIL: ${TRAEFIK_ACME_EMAIL}

      # TRAEFIK_ACME_CASERVER: 'https://acme-v02.api.letsencrypt.org/directory'
      TRAEFIK_ACME_CASERVER: ${TRAEFIK_ACME_CASERVER:-https://acme-staging-v02.api.letsencrypt.org/directory}

      TRAEFIK_ACME_LOGGING: "${TRAEFIK_ACME_LOGGING:-false}"

      # enable admin dashboard under /dashboard/
      TRAEFIK_ADMIN_ENABLE: "${TRAEFIK_ADMIN_ENABLE:-true}"
      TRAEFIK_ADMIN_GENERATE_RULE: ${TRAEFIK_ADMIN_GENERATE_RULE:-false}
      TRAEFIK_ADMIN_SSL: "${TRAEFIK_ADMIN_SSL:-false}"
      # this ensure we do not bind /dashboard/ on all traefik hosts, only the one we dedicate for the admin access
      TRAEFIK_ADMIN_DOMAIN: "${TRAEFIK_ADMIN_DOMAIN:-www.traefik.${BASEDOMAIN}}"
      # # create a password via `docker run -it httpd htpasswd -sbn admin yourpw`
      # # the default here is admin/admin
      TRAEFIK_ADMIN_AUTH_USERS:
      # docker
      TRAEFIK_DOCKER_ENABLE: 'true'
      TRAEFIK_DOCKER_DEFAULT_RULE: "Host(`{{ ( normalize .Name ) }}.${BASEDOMAIN}`)"
      TRAEFIK_DOCKER_EXPOSEDBYDEFAULT: "${TRAEFIK_DOCKER_EXPOSEDBYDEFAULT:-true}"

      # misc
      TRAEFIK_FILE_ENABLE: 'true'
      TRAEFIK_INSECURE_SKIP: 'true'
      TRAEFIK_DEBUG: 'false'
      TRAEFIK_LOG_LEVEL: 'ERROR'
    volumes:
      - ${FILESTORAGE:-./traefik-file-examples}:/mnt/filestorage
      - certs:/mnt/certs
      - acme:/mnt/acme
      # mount our docker socket so our docker container can be discovered
      #- /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${TRAEFIK_HTTP_PORT:-80}:8080
      - ${TRAEFIK_HTTPS_PORT:-443}:8443
    labels:
      # create a password via `docker run -it httpd htpasswd -bn test yourpw`
      # the default here is admin/admin
      traefik.docker.network: 'traefik'
      # do not expose this service via an auto-rule - needed since TRAEFIK_DOCKER_EXPOSEDBYDEFAULT=true
      traefik.enable: false
volumes:
  acme:
  certs:
