[http.services]  
  [http.services.gateway.loadBalancer]  
    [[http.services.gateway.loadBalancer.servers]]  
      url = "https://gateway.myself.com:80"

[http.routers]  
  [http.routers.gateway]  
    service = "gateway" 
    rule = "Host(`www.gateway.myself.com`)"  
  [http.routers.gateway.tls] 
    certResolver = "default"      