[http.services]  
  [http.services.homeautomation.loadBalancer]  
    [[http.services.homeautomation.loadBalancer.servers]]  
      url = "http://homeautomation.myself.com:80"

[http.routers]  
  [http.routers.homeautomation]  
    service = "homeautomation" 
    rule = "Host(`www.homeautomation.myself.com`)"  
  [http.routers.homeautomation.tls] 
    certResolver = "default"
